import { api } from "../../xpnz.config.js"
import { sample } from "lodash-es"

export const expenseNames = [
  "Coffee Break ☕",
  "Pet Supplies 🐾",
  "Book Club 📚",
  "Movie Night 🎬",
  "Travel Fund ✈️",
  "Art Supplies 🎨",
  "Game Night 🎲",
  "Concert Tickets 🎟️",
  "Tech Gadgets 📱",
  "Gardening Tools 🌱",
  "Pizza Party 🍕",
  "Ice Cream Treats 🍦",
  "Sunday Brunch 🍳",
  "Fitness Club 🏋️",
  "Spa Day 💆",
  "Chocolate Stash 🍫",
  "Sushi Date 🍣",
  "Beach Day 🏖️",
  "Happy Hour 🍹",
  "Cheese Platter 🧀",
  "DIY Projects 🔨",
  "Tea Time 🫖",
  "Vegan Snacks 🥑",
  "Wine Night 🍷",
  "Burger Bash 🍔",
  "Music Streaming 🎵",
  "Magic Show 🎩",
  "Vintage Finds 🕰️",
  "Plant Babies 🪴",
  "Candle Collection 🕯️",
  "Makeup Magic 💄",
  "Baking Bonanza 🧁",
  "Holiday Gifts 🎁",
  "Car Wash 🚗",
  "Photography 📸",
  "Knitting Kit 🧶",
  "Craft Beer 🍺",
  "Smoothie Sips 🥤",
  "Science Fiction 🛸",
  "Sports Gear ⚽",
  "Picnic Party 🧺",
  "Comedy Club 😂",
  "Thrift Shopping 🛍️",
  "Aquarium Visit 🐠",
  "Skate Session 🛹",
  "Ballet Tickets 🩰",
  "Poetry Books 📖",
  "Farmers Market 🥦",
  "Star Gazing 🔭",
  "Puzzle Pieces 🧩",
  "Herbal Remedies 🌿",
  "Video Games 🎮",
  "Jazz Night 🎷",
  "Camping Trip ⛺",
  "Fast Food Frenzy 🍟",
  "New Sneakers 👟",
  "Online Course 🖥️",
  "Fishing Trip 🎣",
  "Tailgate Party 🍗",
  "Ghost Tour 👻"
]

export function getRandomExpenseName() {
  return sample(expenseNames)
}

export const emptyExpense = {
  id: "",
  name: "",
  amount: "",
  currency: "",
  income: false,
  date: new Date(),
  category: "",
  paidBy: [], // [{ member: string, amount: number }]
  splitBetween: [] // [{ member: string, weight: number, normalizedWeight: number }]
}

export async function getExpenses(ledger) {
  const expensesPromise = fetch(`${api.base}/transactions?ledger=${ledger}`, { cache: "no-store" })
    .then((res) => res.json())
    .then((expenses) => {
      expenses.forEach((d) => {
        d.income = d.expense_type === "income"
        d.paidBy = d.contributions.map((c) => ({ member: c.member, amount: c.paid })).filter((c) => c.amount > 0)
        d.splitBetween = d.contributions
          .map((c) => ({ member: c.member, weight: c.weight, normalizedWeight: c.owes }))
          .filter((c) => c.weight > 0)
      })
      return expenses
    })

  const balancesPromise = fetch(`${api.base}/ledgers/${ledger}/balance`, { cache: "no-store" }).then((res) =>
    res.json()
  )
  const debtsPromise = fetch(`${api.base}/ledgers/${ledger}/settlement`, { cache: "no-store" }).then((res) =>
    res.json()
  )

  const [expenses, balances, debts] = await Promise.all([expensesPromise, balancesPromise, debtsPromise])

  return { expenses, balances, debts }
}

export const currencies = {
  CAD: "🇨🇦 CAD",
  USD: "🇺🇸 USD",
  EUR: "🇪🇺 EUR",
  JPY: "🇯🇵 JPY",
  GBP: "🇬🇧 GBP",
  PLN: "🇵🇱 PLN",
  CNY: "🇨🇳 CNY",
  INR: "🇮🇳 INR",
  RUB: "🇷🇺 RUB",
  BRL: "🇧🇷 BRL",
  MXN: "🇲🇽 MXN",
  AUD: "🇦🇺 AUD",
  KRW: "🇰🇷 KRW",
  IDR: "🇮🇩 IDR",
  TRY: "🇹🇷 TRY",
  ZAR: "🇿🇦 ZAR",
  NGN: "🇳🇬 NGN",
  SEK: "🇸🇪 SEK"
}

export const currencySymbols = {
  AED: "د.إ",
  AFN: "؋",
  ALL: "L",
  AMD: "֏",
  ANG: "ƒ",
  AOA: "Kz",
  ARS: "$",
  AUD: "$",
  AWG: "ƒ",
  AZN: "₼",
  BAM: "KM",
  BBD: "$",
  BDT: "৳",
  BGN: "лв",
  BHD: ".د.ب",
  BIF: "FBu",
  BMD: "$",
  BND: "$",
  BOB: "$b",
  BOV: "BOV",
  BRL: "R$",
  BSD: "$",
  BTC: "₿",
  BTN: "Nu.",
  BWP: "P",
  BYN: "Br",
  BYR: "Br",
  BZD: "BZ$",
  CAD: "$",
  CDF: "FC",
  CHE: "CHE",
  CHF: "CHF",
  CHW: "CHW",
  CLF: "CLF",
  CLP: "$",
  CNH: "¥",
  CNY: "¥",
  COP: "$",
  COU: "COU",
  CRC: "₡",
  CUC: "$",
  CUP: "₱",
  CVE: "$",
  CZK: "Kč",
  DJF: "Fdj",
  DKK: "kr",
  DOP: "RD$",
  DZD: "دج",
  EEK: "kr",
  EGP: "£",
  ERN: "Nfk",
  ETB: "Br",
  ETH: "Ξ",
  EUR: "€",
  FJD: "$",
  FKP: "£",
  GBP: "£",
  GEL: "₾",
  GGP: "£",
  GHC: "₵",
  GHS: "GH₵",
  GIP: "£",
  GMD: "D",
  GNF: "FG",
  GTQ: "Q",
  GYD: "$",
  HKD: "$",
  HNL: "L",
  HRK: "kn",
  HTG: "G",
  HUF: "Ft",
  IDR: "Rp",
  ILS: "₪",
  IMP: "£",
  INR: "₹",
  IQD: "ع.د",
  IRR: "﷼",
  ISK: "kr",
  JEP: "£",
  JMD: "J$",
  JOD: "JD",
  JPY: "¥",
  KES: "KSh",
  KGS: "лв",
  KHR: "៛",
  KMF: "CF",
  KPW: "₩",
  KRW: "₩",
  KWD: "KD",
  KYD: "$",
  KZT: "₸",
  LAK: "₭",
  LBP: "£",
  LKR: "₨",
  LRD: "$",
  LSL: "M",
  LTC: "Ł",
  LTL: "Lt",
  LVL: "Ls",
  LYD: "LD",
  MAD: "MAD",
  MDL: "lei",
  MGA: "Ar",
  MKD: "ден",
  MMK: "K",
  MNT: "₮",
  MOP: "MOP$",
  MRO: "UM",
  MRU: "UM",
  MUR: "₨",
  MVR: "Rf",
  MWK: "MK",
  MXN: "$",
  MXV: "MXV",
  MYR: "RM",
  MZN: "MT",
  NAD: "$",
  NGN: "₦",
  NIO: "C$",
  NOK: "kr",
  NPR: "₨",
  NZD: "$",
  OMR: "﷼",
  PAB: "B/.",
  PEN: "S/.",
  PGK: "K",
  PHP: "₱",
  PKR: "₨",
  PLN: "zł",
  PYG: "Gs",
  QAR: "﷼",
  RMB: "￥",
  RON: "lei",
  RSD: "Дин.",
  RUB: "₽",
  RWF: "R₣",
  SAR: "﷼",
  SBD: "$",
  SCR: "₨",
  SDG: "ج.س.",
  SEK: "kr",
  SGD: "S$",
  SHP: "£",
  SLL: "Le",
  SOS: "S",
  SRD: "$",
  SSP: "£",
  STD: "Db",
  STN: "Db",
  SVC: "$",
  SYP: "£",
  SZL: "E",
  THB: "฿",
  TJS: "SM",
  TMT: "T",
  TND: "د.ت",
  TOP: "T$",
  TRL: "₤",
  TRY: "₺",
  TTD: "TT$",
  TVD: "$",
  TWD: "NT$",
  TZS: "TSh",
  UAH: "₴",
  UGX: "USh",
  USD: "$",
  UYI: "UYI",
  UYU: "$U",
  UYW: "UYW",
  UZS: "лв",
  VEF: "Bs",
  VES: "Bs.S",
  VND: "₫",
  VUV: "VT",
  WST: "WS$",
  XAF: "FCFA",
  XBT: "Ƀ",
  XCD: "$",
  XOF: "CFA",
  XPF: "₣",
  XSU: "Sucre",
  XUA: "XUA",
  YER: "﷼",
  ZAR: "R",
  ZMW: "ZK",
  ZWD: "Z$",
  ZWL: "$"
}
